Repository AY2021S1-CS2113-T16-4/tp, pull requests merged in 2020-10, with the labels that each got.

#15 Add necessary base classes
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/ExitCommand.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/exception/RexException.java
  src/main/java/seedu/rex/data/patient/Patient.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
  src/test/java/seedu/rex/RexTest.java
  src/test/java/seedu/rex/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#17 Add JUnit test to Ui
  src/test/java/seedu/rex/ui/UiTest.java
Labels: priority.Medium, type.Task

#19 Add more classes
  src/main/java/seedu/rex/data/DoctorList.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/data/hospital/Doctor.java
  src/main/java/seedu/rex/data/hospital/Hospital.java
  src/main/java/seedu/rex/data/hospital/Patient.java
  src/main/java/seedu/rex/data/hospital/Prescription.java
  src/main/java/seedu/rex/data/patient/Patient.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/test/java/seedu/rex/parser/ParserTest.java
Labels: priority.High, type.Task

#20 Add ability to add new patients
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/data/hospital/Patient.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
Labels: priority.High, type.Story

#21 Add ability to retrieve patient's details
  .gitignore
  build.gradle
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/hospital/Patient.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
  src/test/java/seedu/rex/commands/CommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#23 Add some assertions to Rex
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
Labels: priority.High, type.Task

#25 Add basic logging
  src/main/java/seedu/rex/Rex.java
Labels: priority.High, type.Task

#27 Add book and create appointment functions
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/BookCommand.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/CreateAppointmentCommand.java
  src/main/java/seedu/rex/commands/ExitCommand.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/AppointmentList.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
Labels: priority.High, type.Story

#29 Fix checkstyle errors
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/BookCommand.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/CreateAppointmentCommand.java
  src/main/java/seedu/rex/commands/ExitCommand.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/AppointmentList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
Labels: priority.Medium, severity.VeryLow, type.Bug

#30 added ability to edit patient details
  src/main/java/seedu/rex/commands/EditCommand.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/ui/Ui.java
Labels: priority.High, type.Story

#32 Delete patient
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/DeleteCommand.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/ui/Ui.java
Labels: priority.High, type.Story

#33 Add minor touchup
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/tanjunhong.md
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/BookCommand.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/CreateAppointmentCommand.java
  src/main/java/seedu/rex/commands/DeleteCommand.java
  src/main/java/seedu/rex/commands/EditCommand.java
  src/main/java/seedu/rex/commands/ExitCommand.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/AppointmentList.java
  src/main/java/seedu/rex/data/DoctorList.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/data/hospital/Doctor.java
  src/main/java/seedu/rex/data/hospital/Hospital.java
  src/main/java/seedu/rex/data/hospital/Patient.java
  src/main/java/seedu/rex/data/hospital/Prescription.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium

#42 Add ability to list patients
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/BookCommand.java
  src/main/java/seedu/rex/commands/CreateAppointmentCommand.java
  src/main/java/seedu/rex/commands/DeleteCommand.java
  src/main/java/seedu/rex/commands/EditCommand.java
  src/main/java/seedu/rex/commands/ListAppointmentsCommand.java
  src/main/java/seedu/rex/commands/ListPatientsCommand.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/PatientList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/data/hospital/Doctor.java
  src/main/java/seedu/rex/data/hospital/Patient.java
  src/main/java/seedu/rex/data/hospital/Prescription.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#44 Add doctor list
  data/doctors.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tanjunhong.md
  src/main/java/seedu/rex/Rex.java
  src/main/java/seedu/rex/commands/AddCommand.java
  src/main/java/seedu/rex/commands/AddDoctorCommand.java
  src/main/java/seedu/rex/commands/BookCommand.java
  src/main/java/seedu/rex/commands/Command.java
  src/main/java/seedu/rex/commands/CreateAppointmentCommand.java
  src/main/java/seedu/rex/commands/DeleteCommand.java
  src/main/java/seedu/rex/commands/EditCommand.java
  src/main/java/seedu/rex/commands/ExitCommand.java
  src/main/java/seedu/rex/commands/ListAppointmentsCommand.java
  src/main/java/seedu/rex/commands/ListPatientsCommand.java
  src/main/java/seedu/rex/commands/RemoveDoctorCommand.java
  src/main/java/seedu/rex/commands/RetrieveCommand.java
  src/main/java/seedu/rex/data/AppointmentList.java
  src/main/java/seedu/rex/data/DoctorList.java
  src/main/java/seedu/rex/data/hospital/Appointment.java
  src/main/java/seedu/rex/data/hospital/Doctor.java
  src/main/java/seedu/rex/parser/Parser.java
  src/main/java/seedu/rex/storage/Storage.java
  src/main/java/seedu/rex/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High
